services:
  voltanet:
    image: voltanet/voltanet:latest
    environment:
      # generate with `openssl rand -base64 32`
      - AUTH_SECRET=you-should-change-this-secret-key
      - NODE_ENV=production
      - HOSTNAME=0.0.0.0
      - PORT=8000
    networks:
      voltanet:
        ipv4_address: 172.0.0.2
    volumes:
      - ./data/voltanet:/app/data
    restart: unless-stopped

networks:
  voltanet:
    ipam:
      config:
        - subnet: 172.0.0.0/24
